In [1]:
import pandas as pd
import numpy as np
import calendar

# EJERCICIO 1

## 1) Limpiar la columna “Date of Publication” para que sea de tipo numérico. En caso de que exista más de un año ej. “[1860?-70?]” ó “1815, [1816]”, dejar cualquiera de los dos.

In [2]:
# Se Importa el un libro de excel de la biblioteca Brookyn
df = pd.read_excel('/Users/acrhonoz./Downloads/prueba python/fragments/Biblioteca de Brooklyn 1.xlsx')
# Se limpia la columna "Date of Publication"
p = df['Date of Publication'].astype(str).str.extract('(\d+)')
# Se rellenan los NaN con 0, pues son años con esto se homologa el tipo de dato de la columna
p = p.fillna(0)
# Se cambia el tipo dato a "int"
p = p.astype(int)
# Se implementan los cambios a la columna en del dataset original
df['Date of Publication'] = p

## 2) Ordenar utilizando la columna “Identifier” de manera ascendente.

In [3]:
# Se crea el dataset con la columna ordenada de forma ascendente 
by_identifier = df.sort_values('Identifier', ascending=True)
# Se muestra que el cambio se haya efectuado
by_identifier

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
315,667,NaN,"pp. 40. G. Bryan & Co: Oxford, 1898",0,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.","ANDREWS, J. - Writer of Verse",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 011652.g.73.
377,3131,NaN,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.","ANDREÌ, John - Major|ARNOLD, Benedict.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9603.g.14.
312,5382,NaN,London,1847,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.","LEECH, John - Artist",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS C.131.d.16.|British Libr...
1155,8239,NaN,Quebec,1899,L. J. Demers & FreÌ€re,"The Plains of Abraham, 1759, a spot sacred to ...",NaN,"BROTANEK, Rudolf.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10470.ff.20.
1064,8440,NaN,London,1894,Effingham Wilson,The New Era of the Goldmining Industry in the ...,"ABRAHAM, FeÌlix - Writer on Mining","SIMONSEN, H. C.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 07108.g.6.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,4114889,NaN,London,1868,NaN,"The 5 Alls. A collection of stories, charades,...",NaN,"HOOD, Thomas - the Younger",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12620.f.17.
1344,4115138,NaN,"G. Eld: London, 1608",0,NaN,The Revenger's Tagaedie. As it hath beene sund...,NaN,"TOURNEUR, Cyril.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 644.c.80.|British Librar...
1060,4157746,NaN,London,1811,F. C. and J. Rivington,"The New Chronicles of England and France, in t...","FABYAN, Robert.","ELLIS, Henry - Sir, Principal Librarian of the...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
1113,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
683,4158128,NaN,Derby,1831,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

## 3) Una vez se tengan los datos ordenados, completar los registros vacíos de la columna “Author” con el autor del registro anterior al que se requiere completar.

In [4]:
# De la columna "Autor" se rellenan los registros con NaN con el nombre del autor de la fila anterior
by_identifier['Author'] = by_identifier['Author'].fillna(method ='ffill')
# Se verifica que el cambio se haya efectuado
by_identifier

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
315,667,NaN,"pp. 40. G. Bryan & Co: Oxford, 1898",0,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.","ANDREWS, J. - Writer of Verse",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 011652.g.73.
377,3131,NaN,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.","ANDREÌ, John - Major|ARNOLD, Benedict.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9603.g.14.
312,5382,NaN,London,1847,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.","LEECH, John - Artist",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS C.131.d.16.|British Libr...
1155,8239,NaN,Quebec,1899,L. J. Demers & FreÌ€re,"The Plains of Abraham, 1759, a spot sacred to ...","A'BECKETT, Gilbert Abbott.","BROTANEK, Rudolf.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10470.ff.20.
1064,8440,NaN,London,1894,Effingham Wilson,The New Era of the Goldmining Industry in the ...,"ABRAHAM, FeÌlix - Writer on Mining","SIMONSEN, H. C.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 07108.g.6.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,4114889,NaN,London,1868,NaN,"The 5 Alls. A collection of stories, charades,...","MEREDITH, Susanna.|WIBERG, Carl Fredrik.","HOOD, Thomas - the Younger",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12620.f.17.
1344,4115138,NaN,"G. Eld: London, 1608",0,NaN,The Revenger's Tagaedie. As it hath beene sund...,"MEREDITH, Susanna.|WIBERG, Carl Fredrik.","TOURNEUR, Cyril.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 644.c.80.|British Librar...
1060,4157746,NaN,London,1811,F. C. and J. Rivington,"The New Chronicles of England and France, in t...","FABYAN, Robert.","ELLIS, Henry - Sir, Principal Librarian of the...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
1113,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
683,4158128,NaN,Derby,1831,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

In [5]:
# Como los libros de excel tienen nombres secuenciales, el proceso realizado anteriormente para 1 libro se 
# puede automatizar de tal forma que lo haga para todos los libros

# Automatización del proceso para los 6 libros de Excel
dataframes = []
a = '1'
for i in range(6):
    df = pd.read_excel(f'/Users/acrhonoz./Downloads/prueba python/fragments/Biblioteca de Brooklyn {a}.xlsx')
    # 1) Limpiar la columna "Date Of Publication"
    p = df['Date of Publication'].astype(str).str.extract('(\d+)')
    p = p.fillna(0)
    p = p.astype(int)
    df['Date of Publication'] = p
    # 2) Ordenar utilizando la columna “Identifier” de manera ascendente.
    by_identifier = df.sort_values('Identifier', ascending=True)
    # 3) Una vez se tengan los datos ordenados, completar los registros vacíos de la columna “Author” con el autor del registro anterior al que se requiere completar.
    by_identifier['Author'] = by_identifier['Author'].fillna(method ='ffill')
    dataframes.append(by_identifier)
    a = '0' + a

In [6]:
# Aunque no se especifica, me tomé el atrevimiento que compilar todos datasets en un solo, cada uno limpio y 
# procesado
# Unión de los 6 Dataframes en 1 solo.
data_frame_completo = pd.concat([dataframes[0],dataframes[1],dataframes[2],dataframes[3],dataframes[4],dataframes[5]], axis=0)

In [7]:
# Al compilar se puede revolver el orden ascendente por el campo "Identifier", por lo que 
# se reordena y se vuelven a llenar los NaN con el autor del renglón anterior
data_frame_completo = data_frame_completo.sort_values('Identifier', ascending=True)
data_frame_completo['Author'] = data_frame_completo['Author'].fillna(method ='ffill')
# Se muestra el dataset completo
data_frame_completo

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
640,206,NaN,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1465,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
1356,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for ...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
662,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
783,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
683,4158128,NaN,Derby,1831,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
1398,4159563,NaN,London,1806,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
75,4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
622,4160339,NaN,London,1834,NaN,Collectanea Topographica et Genealogica. [Firs...,"Mackenzie, E. (Eneas)","BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

# EJERCICIO 2

## Crear y entregar un archivo CSV o XLSX con las fechas donde existe cambio de horario en México. Las fechas deberán correr desde 1996 hasta el año 2100. Al año se tienen dos fechas con cambio de horario: el primer domingo de cada abril y el último domingo de octubre.

In [8]:
# Haciendo uso de la librería "calendar" se obtiene el primer domingo de Abril y el último domingo de Octubre
# de esta forma se localizan los principios y finales del horario de verano
# se repite el proceso, iniciando en 1996 y finalizando en 2100
# y se Imprimen las fechas en las habrá inicio y fin de horario de verano

for i in range(1996,2101):
    abril = calendar.month(i,4)
    print('Inicio de horario de verano: ' + abril[56] + '/' + 'Abril' + '/' + str(i))
    octubre = calendar.month(i,10)
    octubre_s = octubre.split("\n")
    octubre_a = np.array(octubre_s[2:])
    if len(octubre_a[4]) != 20:
        print('Termina Horario de verano: ' + octubre_a[3][18] + octubre_a[3][19] +'/'+ 'Octubre' +'/'+ str(i))
    else:
        print('Termina Horario de verano: ' + octubre_a[4][18] + octubre_a[4][19] +'/'+ 'Octubre' +'/'+ str(i))    
    print()

Inicio de horario de verano: 7/Abril/1996
Termina Horario de verano: 27/Octubre/1996

Inicio de horario de verano: 6/Abril/1997
Termina Horario de verano: 26/Octubre/1997

Inicio de horario de verano: 5/Abril/1998
Termina Horario de verano: 25/Octubre/1998

Inicio de horario de verano: 4/Abril/1999
Termina Horario de verano: 31/Octubre/1999

Inicio de horario de verano: 2/Abril/2000
Termina Horario de verano: 29/Octubre/2000

Inicio de horario de verano: 1/Abril/2001
Termina Horario de verano: 28/Octubre/2001

Inicio de horario de verano: 7/Abril/2002
Termina Horario de verano: 27/Octubre/2002

Inicio de horario de verano: 6/Abril/2003
Termina Horario de verano: 26/Octubre/2003

Inicio de horario de verano: 4/Abril/2004
Termina Horario de verano: 31/Octubre/2004

Inicio de horario de verano: 3/Abril/2005
Termina Horario de verano: 30/Octubre/2005

Inicio de horario de verano: 2/Abril/2006
Termina Horario de verano: 29/Octubre/2006

Inicio de horario de verano: 1/Abril/2007
Termina Horario de verano: 28/Octubre/2007

Inicio de horario de verano: 6/Abril/2008
Termina Horario de verano: 26/Octubre/2008

Inicio de horario de verano: 5/Abril/2009
Termina Horario de verano: 25/Octubre/2009

Inicio de horario de verano: 4/Abril/2010
Termina Horario de verano: 31/Octubre/2010

Inicio de horario de verano: 3/Abril/2011
Termina Horario de verano: 30/Octubre/2011

Inicio de horario de verano: 1/Abril/2012
Termina Horario de verano: 28/Octubre/2012

Inicio de horario de verano: 7/Abril/2013
Termina Horario de verano: 27/Octubre/2013

Inicio de horario de verano: 6/Abril/2014
Termina Horario de verano: 26/Octubre/2014

Inicio de horario de verano: 5/Abril/2015
Termina Horario de verano: 25/Octubre/2015

Inicio de horario de verano: 3/Abril/2016
Termina Horario de verano: 30/Octubre/2016

Inicio de horario de verano: 2/Abril/2017
Termina Horario de verano: 29/Octubre/2017

Inicio de horario de verano: 1/Abril/2018
Termina Horario de verano: 28/Octubre/2018

Inicio de horario de verano: 7/Abril/2019
Termina Horario de verano: 27/Octubre/2019

Inicio de horario de verano: 5/Abril/2020
Termina Horario de verano: 25/Octubre/2020

Inicio de horario de verano: 4/Abril/2021
Termina Horario de verano: 31/Octubre/2021

Inicio de horario de verano: 3/Abril/2022
Termina Horario de verano: 30/Octubre/2022

Inicio de horario de verano: 2/Abril/2023
Termina Horario de verano: 29/Octubre/2023

Inicio de horario de verano: 7/Abril/2024
Termina Horario de verano: 27/Octubre/2024

Inicio de horario de verano: 6/Abril/2025
Termina Horario de verano: 26/Octubre/2025

Inicio de horario de verano: 5/Abril/2026
Termina Horario de verano: 25/Octubre/2026

Inicio de horario de verano: 4/Abril/2027
Termina Horario de verano: 31/Octubre/2027

Inicio de horario de verano: 2/Abril/2028
Termina Horario de verano: 29/Octubre/2028

Inicio de horario de verano: 1/Abril/2029
Termina Horario de verano: 28/Octubre/2029

Inicio de horario de verano: 7/Abril/2030
Termina Horario de verano: 27/Octubre/2030

Inicio de horario de verano: 6/Abril/2031
Termina Horario de verano: 26/Octubre/2031

Inicio de horario de verano: 4/Abril/2032
Termina Horario de verano: 31/Octubre/2032

Inicio de horario de verano: 3/Abril/2033
Termina Horario de verano: 30/Octubre/2033

Inicio de horario de verano: 2/Abril/2034
Termina Horario de verano: 29/Octubre/2034

Inicio de horario de verano: 1/Abril/2035
Termina Horario de verano: 28/Octubre/2035

Inicio de horario de verano: 6/Abril/2036
Termina Horario de verano: 26/Octubre/2036

Inicio de horario de verano: 5/Abril/2037
Termina Horario de verano: 25/Octubre/2037

Inicio de horario de verano: 4/Abril/2038
Termina Horario de verano: 31/Octubre/2038

Inicio de horario de verano: 3/Abril/2039
Termina Horario de verano: 30/Octubre/2039

Inicio de horario de verano: 1/Abril/2040
Termina Horario de verano: 28/Octubre/2040

Inicio de horario de verano: 7/Abril/2041
Termina Horario de verano: 27/Octubre/2041

Inicio de horario de verano: 6/Abril/2042
Termina Horario de verano: 26/Octubre/2042

Inicio de horario de verano: 5/Abril/2043
Termina Horario de verano: 25/Octubre/2043

Inicio de horario de verano: 3/Abril/2044
Termina Horario de verano: 30/Octubre/2044

Inicio de horario de verano: 2/Abril/2045
Termina Horario de verano: 29/Octubre/2045

Inicio de horario de verano: 1/Abril/2046
Termina Horario de verano: 28/Octubre/2046

Inicio de horario de verano: 7/Abril/2047
Termina Horario de verano: 27/Octubre/2047

Inicio de horario de verano: 5/Abril/2048
Termina Horario de verano: 25/Octubre/2048

Inicio de horario de verano: 4/Abril/2049
Termina Horario de verano: 31/Octubre/2049

Inicio de horario de verano: 3/Abril/2050
Termina Horario de verano: 30/Octubre/2050

Inicio de horario de verano: 2/Abril/2051
Termina Horario de verano: 29/Octubre/2051

Inicio de horario de verano: 7/Abril/2052
Termina Horario de verano: 27/Octubre/2052

Inicio de horario de verano: 6/Abril/2053
Termina Horario de verano: 26/Octubre/2053

Inicio de horario de verano: 5/Abril/2054
Termina Horario de verano: 25/Octubre/2054

Inicio de horario de verano: 4/Abril/2055
Termina Horario de verano: 31/Octubre/2055

Inicio de horario de verano: 2/Abril/2056
Termina Horario de verano: 29/Octubre/2056

Inicio de horario de verano: 1/Abril/2057
Termina Horario de verano: 28/Octubre/2057

Inicio de horario de verano: 7/Abril/2058
Termina Horario de verano: 27/Octubre/2058

Inicio de horario de verano: 6/Abril/2059
Termina Horario de verano: 26/Octubre/2059

Inicio de horario de verano: 4/Abril/2060
Termina Horario de verano: 31/Octubre/2060

Inicio de horario de verano: 3/Abril/2061
Termina Horario de verano: 30/Octubre/2061

Inicio de horario de verano: 2/Abril/2062
Termina Horario de verano: 29/Octubre/2062

Inicio de horario de verano: 1/Abril/2063
Termina Horario de verano: 28/Octubre/2063

Inicio de horario de verano: 6/Abril/2064
Termina Horario de verano: 26/Octubre/2064

Inicio de horario de verano: 5/Abril/2065
Termina Horario de verano: 25/Octubre/2065

Inicio de horario de verano: 4/Abril/2066
Termina Horario de verano: 31/Octubre/2066

Inicio de horario de verano: 3/Abril/2067
Termina Horario de verano: 30/Octubre/2067

Inicio de horario de verano: 1/Abril/2068
Termina Horario de verano: 28/Octubre/2068

Inicio de horario de verano: 7/Abril/2069
Termina Horario de verano: 27/Octubre/2069

Inicio de horario de verano: 6/Abril/2070
Termina Horario de verano: 26/Octubre/2070

Inicio de horario de verano: 5/Abril/2071
Termina Horario de verano: 25/Octubre/2071

Inicio de horario de verano: 3/Abril/2072
Termina Horario de verano: 30/Octubre/2072

Inicio de horario de verano: 2/Abril/2073
Termina Horario de verano: 29/Octubre/2073

Inicio de horario de verano: 1/Abril/2074
Termina Horario de verano: 28/Octubre/2074

Inicio de horario de verano: 7/Abril/2075
Termina Horario de verano: 27/Octubre/2075

Inicio de horario de verano: 5/Abril/2076
Termina Horario de verano: 25/Octubre/2076

Inicio de horario de verano: 4/Abril/2077
Termina Horario de verano: 31/Octubre/2077

Inicio de horario de verano: 3/Abril/2078
Termina Horario de verano: 30/Octubre/2078

Inicio de horario de verano: 2/Abril/2079
Termina Horario de verano: 29/Octubre/2079

Inicio de horario de verano: 7/Abril/2080
Termina Horario de verano: 27/Octubre/2080

Inicio de horario de verano: 6/Abril/2081
Termina Horario de verano: 26/Octubre/2081

Inicio de horario de verano: 5/Abril/2082
Termina Horario de verano: 25/Octubre/2082

Inicio de horario de verano: 4/Abril/2083
Termina Horario de verano: 31/Octubre/2083

Inicio de horario de verano: 2/Abril/2084
Termina Horario de verano: 29/Octubre/2084

Inicio de horario de verano: 1/Abril/2085
Termina Horario de verano: 28/Octubre/2085

Inicio de horario de verano: 7/Abril/2086
Termina Horario de verano: 27/Octubre/2086

Inicio de horario de verano: 6/Abril/2087
Termina Horario de verano: 26/Octubre/2087

Inicio de horario de verano: 4/Abril/2088
Termina Horario de verano: 31/Octubre/2088

Inicio de horario de verano: 3/Abril/2089
Termina Horario de verano: 30/Octubre/2089

Inicio de horario de verano: 2/Abril/2090
Termina Horario de verano: 29/Octubre/2090

Inicio de horario de verano: 1/Abril/2091
Termina Horario de verano: 28/Octubre/2091

Inicio de horario de verano: 6/Abril/2092
Termina Horario de verano: 26/Octubre/2092

Inicio de horario de verano: 5/Abril/2093
Termina Horario de verano: 25/Octubre/2093

Inicio de horario de verano: 4/Abril/2094
Termina Horario de verano: 31/Octubre/2094

Inicio de horario de verano: 3/Abril/2095
Termina Horario de verano: 30/Octubre/2095

Inicio de horario de verano: 1/Abril/2096
Termina Horario de verano: 28/Octubre/2096

Inicio de horario de verano: 7/Abril/2097
Termina Horario de verano: 27/Octubre/2097

Inicio de horario de verano: 6/Abril/2098
Termina Horario de verano: 26/Octubre/2098

Inicio de horario de verano: 5/Abril/2099
Termina Horario de verano: 25/Octubre/2099

Inicio de horario de verano: 4/Abril/2100
Termina Horario de verano: 31/Octubre/2100

In [9]:
# Creo una subrutina que me almacene cada inicio y cada termino en 2 listas, una para tipo de dato
# con ello creo un diccionario que tenga 2 campos "Inicio" y 'Termino'
# Transformo ese diccionario a un dataframe y lo exporto a un libro de excel
# las fechas quedan con el formaro "aaaammd" para el inicio y "aaaammdd" para el termino
lista_inicio = []
lista_termino = []
dic = {'Inicio': '', 'Termino': ''} 
for i in range(1996,2101):
    abril = calendar.month(i,4)
    lista_inicio.append(int(str(i) + '04' + abril[56]))    
    octubre = calendar.month(i,10)
    octubre_s = octubre.split("\n")
    octubre_a = np.array(octubre_s[2:])
    if len(octubre_a[4]) != 20:
        lista_termino.append(int(str(i) + '10' + octubre_a[3][18] + octubre_a[3][19]))
    else:
        lista_termino.append(int(str(i) + '10' + octubre_a[4][18] + octubre_a[4][19]))
dic['Inicio'] = lista_inicio
dic['Termino'] = lista_termino
df_Ho_ver = pd.DataFrame(dic)
df_Ho_ver.to_excel('/Users/acrhonoz./Desktop/Horario_Verano.xlsx')